# Generated by Django 4.2.4 on 2023-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='points',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
